title: Robolithic
description: Innovating the Future with Robotics & Automation

# Social Links
social:
  twitter: robolithic
  linkedin: robolithic

# Email Address
email: info@robolithic.com

# Theme
theme: jekyll-theme-cayman
# URL
#url: "www.robolithic.com" 

# Navigation Pages
header_pages:
  - index.md
  - services.md
  - contact.md
